### ISSUE TITLE
[Feature request] IDNA2008 standard for punycode

### ISSUE THREAD

**Issue by Kristinita** [furikake/sublime-codec#14]
### 1. Request

It would be nice, if you add IDNA2008 standard support for punycode like **<https://www.punycoder.com/>**.

### 2. Justification

For example, I have a link:

    http://www.россия.рф/

If I convert link in **<https://www.punycoder.com/>**, I get result:

    http://www.xn--h1alffa9f.xn--p1ai/

This link successful open in browsers.

If I convert link use your package, I get result:

    http://www../-e5k3f5adpa7dun

If I insert this link in URL bar → I press <kbd>Enter</kbd> → link don't open for me → Firefox and Chrome hangs.

### 3. Desirable behavior

I select `http://www.россия.рф/` → <kbd>Ctrl+Shift+P</kbd> → `Codec: Punycode encode` → link convert to **<http://www.xn--h1alffa9f.xn--p1ai/>**.

Thanks.

**Comment by furikake** [comment]
Good idea. I'll add that for the next release

**Comment by furikake** [comment]
I had a quick look at how this would be implemented.

If you use `www.россия.рф` as the input then it will generate the output you're looking for.
If you use `http://www.россия.рф` then it won't convert as `:` is not allowed.

**Comment by furikake** [comment]
Hah. I just realised that you were using Punycode rather than IDNA. If you use IDNA on the domain name portion then it would have worked.  I just released v1.4.1 with IDNA 2008 support.  In case anyone stumbles upon this:

IDNA 2003: faß.de -> fass.de
IDNA 2008: faß.de -> xn--fa-hia.de
IDNA 2008 UTS46: faß.de -> xn--fa-hia.de
IDNA 2008 transitional: faß.de -> fass.de

IDNA 2003: ÖBB.at -> xn--bb-eka.at
IDNA 2008: ÖBB.at -> ÖBB.at (fails due to Ö)
IDNA 2008 UTS46: ÖBB.at -> xn--bb-eka.at
IDNA 2008 transitional: ÖBB.at -> xn--bb-eka.at

IDNA 2003: 日本語。ＪＰ -> xn--wgv71a119e.jp
IDNA 2008: 日本語。ＪＰ -> 日本語。ＪＰ (fails due to 。)
IDNA 2008 UTS46: 日本語。ＪＰ -> xn--wgv71a119e.jp
IDNA 2008 transitional: 日本語。ＪＰ -> xn--wgv71a119e.jp
